### ISSUE TITLE
ModuleNotFoundError: No module named 'rosbag'

### ISSUE THREAD

**Issue by l067** [hshi74/robocook#2]
Hello, Thanks for your great work.
I followed the instructions to activate the environment. But when I ran the .sh file, e.g. "bash scripts/perception/perception.sh", there was an error "ModuleNotFoundError: No module named 'rosbag'". And I didn't see the rosbag in the environment.yml.

I tried some ways to install the rosbag and ros_numpy packages, but all my attempts failed. Could you please tell me what the correct way to install these two packages?

**Comment by hshi74** [comment]
Hello, thanks for your interest in our work and for bringing this issue up.

Yes, I remember that was a pain point when I set up the environment, but unfortunately, I don't remember the exact way to address this issue. Here are two potential solutions.

1. If you're not against installing ROS on your computer, that is one thing you can try. I'm 50% sure that was how I resolved this. You will need to set up the environment variables properly so that your Python can find those packages in the ROS installation.
1. Here's another package you can try: [robocraft.yml](https://github.com/hshi74/robocraft/blob/b428322ec46bc717a9d0f9e5b9c2c6514193e0b0/robocraft.yml#L112)

In terms of ros_numpy, maybe try these two ways:
1. [robocraft.yml](https://github.com/hshi74/robocraft/blob/b428322ec46bc717a9d0f9e5b9c2c6514193e0b0/robocraft.yml#L231)
1. [https://answers.ros.org/question/270439/ros_numpy-package/](https://answers.ros.org/question/270439/ros_numpy-package/)

Since our raw data is collected vis control code written in ROS and stored in rosbags, our code is mingled with ROS dependencies, which should have been optimized. Sorry for any inconvenience. Let me know what works for you!

**Comment by l067** [comment]
Thank you for your suggestions; I've resolved the ROS issue. However, I've encountered another potential problem. In your planning/pcd_tool_classifier/train.py script, it appears that the ToolDataset should be in an image data format. Yet, in the provided tool_classification.tar.xz file, the data format is a point cloud. This discrepancy has left me confused about whether I should use point cloud data or images as the input for tool classification.
